version: '3.8'

services:
  # Database 1: Postgres (Credentials/Authentication)
  auth-db:
    image: postgres:15
    container_name: leave-app-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dC_it@gn25?
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend: FastAPI
  api:
    build: ./backend
    container_name: leave-app-api
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    environment:
      # --- PostgreSQL Config (Auth) ---
      - PG_USER=postgres
      - PG_PASS=dC_it@gn25?
      - PG_HOST=auth-db
      - PG_PORT=5432
      - PG_DB=auth_db
      
      # --- SQL Server Config (Payroll) ---
      - SQL_USER=sa
      - SQL_PASS=Ftp@2024?
      - SQL_HOST=172.96.10.78 
      - SQL_PORT=1433
      - SQL_DB=PayrollDB

  # Frontend: Vite
  web:
    build: ./frontend
    command: npm run dev -- --host
    container_name: leave-app-web
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data: